### ISSUE TITLE
CSS grid

### ISSUE THREAD

**Issue by PolluxLee** [PolluxLee/blog#11]
## grid
```css
#garden {
  display: grid;
  grid-template-columns: 20% 20% 20% 20% 20%;
  grid-template-rows: 20% 20% 20% 20% 20%;
}
```

## grid-column-start

网格将要放置对象的起始位置

- [integer]：第几个
- span [integer]：跨越两格

## grid-column-end

网格将要放置对象的结束位置的后一位

- [integer]：第几个
- span [integer]：跨越两格

比如要放置 {1,2,3} 这三个位置，则 **左开右闭**
```
#water {
  grid-column-start: 1;
  grid-column-end: 4;
  // grid-column-end: span 3
}
```

## grid-column

grid-column-start 和 grid-column-end 的合体

## grid-row

grid-row-start 和 grid-row-end 的合体

## grid-area

四个值分别是
grid-row-start，grid-column-start，grid-row-end，grid-column-end

```
#water {
   grid-area: 1/2/4/-1;
}
```

## order

网格项目的顺序，类似于 z-index，默认值为 0

- [integer]

## grid-template-rows + grid-template-columns = grid-template

```
// 可使用单位 px em % fr 等等，其中 fr 为比例
#garden {
  display: grid;
  grid-template-columns: repeat(8, 12.5%); // 8 个 12.5% 重复
  grid-template-rows: 20% 20% 20% 20% 20%;
}
```
