### ISSUE TITLE
CSS loading

### ISSUE THREAD

**Issue by PolluxLee** [PolluxLee/blog#14]
### Loading

![](https://upload-images.jianshu.io/upload_images/2351420-e6514438b6b97f94.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### twinkle.html
```html
<div class="loading">
  <div class="loading__content">
    <div class="loading__content--circle circle1"></div>
    <div class="loading__content--circle circle2"></div>
    <div class="loading__content--circle circle3"></div>
  </div>
</div>
```

### twinkle.scss
```SCSS
$orange: #D35400;
$circle-width: 16px;
$circle-height: 16px;

.loading {
  background-color: $orange;
  width: 100vw;
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  &__content {
    letter-spacing: 5px;
    &--circle {
      width: $circle-width;
      height: $circle-height;
      background-color: white;
      display: inline-block;
      border-radius: 50%;
      animation: twinkle 1.2s infinite ease-in-out;
      -webkit-animation: twinkle 1.2s infinite ease-in-out;
    }
  }
}

.circle1 { animation-delay: 0s; -webkit-animation-delay: 0s; }
.circle2 { animation-delay: 0.1s; -webkit-animation-delay: 0.1s; }
.circle3 { animation-delay: 0.2s; -webkit-animation-delay: 0.2s; }

@keyframes twinkle {
  0%,40%,100% {
    transform: scale(1); 
    -webkit-transform: scale(1);
  }
  20% {
    transform: scale(0); 
    -webkit-transform: scale(0);
  } 
}
```

### Full Demo

[Demo](https://stackblitz.com/edit/polluxlee-keyframe)
