### ISSUE TITLE
Less Variables 变量

### ISSUE THREAD

**Issue by PolluxLee** [PolluxLee/blog#65]
## Overview

```less
@width: 10px;
@height: @width + 10px;

#header {
  width: @width;
  height: @height;
}
```

## Variable Interpolation 变量插值

**Selectors**
```less
// Variables
@my-selector: banner;

// Usage
.@{my-selector} {
  font-weight: bold;
  line-height: 40px;
  margin: 0 auto;
}
```

**URLs**
```less
// Variables
@images: "../img";

// Usage
body {
  color: #444;
  background: url("@{images}/white-sand.png");
}
```

**Properties**

```less
@property: color;

.widget {
  @{property}: #0ee;
  background-@{property}: #999;
}
```

## Variable Variables 变量的变量

```less
@primary:  green;
@secondary: blue;

.section {
  @color: primary;

  .element {
    color: @@color;
  }
}
```

## Lazy Evaluation 懒声明

类似 JavaScript 作用域链，当前的作用域会覆盖前面的前面的作用域，在作用域中，变量不需要先声明，如果作用域中有同名的变量，即取最后一个作为最终值

```less
@var: 0;
.class {
  @var: 1;
  .brass {
    @var: 2;
    three: @var;
    @var: 3;
  }
  one: @var;
}
```

## Properties as Variables 属性作为变量

不需要专门声明变量，直接将能够被访问到的属性当成某个属性的变量

```less
.block {
  color: red; 
  .inner {
    background-color: $color; 
  }
  color: blue;  
} 
```

**编译后：**

```CSS
.block {
  color: red; 
  color: blue;  
} 
.block .inner {
  background-color: blue; 
}
```
