### ISSUE TITLE
Less Mixins 混入

### ISSUE THREAD

**Issue by PolluxLee** [PolluxLee/blog#66]
## Mixins

```less
// Mixins
.a, #b {
  color: red;
}
```

**如果不想要在 CSS 中编译出 Mixins，则在 Mixins 后加 `()`**

```less
// Mixins
.a(), #b() {
  color: red;
}
```

```
// usage
.mixin-class {
  .a();
}
.mixin-id {
  #b();
}
```

## Namespaces 命名空间

**像这样写可以很方便地管理 Mixins：**

```less
#bundle() {
  .button {
    display: block;
    border: 1px solid black;
    background-color: grey;
    &:hover {
      background-color: white;
    }
  }
  .tab { ... }
  .citation { ... }
}
```

下面的几个操作是等价的：

```less
#bundle.tab
#bundle .tab
#bundle > .tab
```

用法：
```less
#header a {
  color: orange;
  #bundle.button();  // can also be written as #bundle > .button
}
```

## Parametric Mixins 可传参混入

**Less**
```less
.mixin(@color: black; @margin: 10px; @padding: 20px) {
  color: @color;
  margin: @margin;
  padding: @padding;
}
.class1 {
  // 无参
  .mixin()
}
.class2 {
  // 具名传参
  .mixin(@margin: 20px; @color: #33acfe);
}

```

**CSS**
```CSS
.class1 {
  color: black;
  margin: 10px;
  padding: 20px;
}
.class2 {
  color: #33acfe;
  margin: 20px;
  padding: 20px;
}

```

## Recursive Mixins 递归混入

一个通用的用递归循环生成 CSS grid 类的例子：

**Less**
```less
.generate-columns(4);

.generate-columns(@n, @i: 1) when (@i =< @n) {
  .column-@{i} {
    width: (@i * 100% / @n);
  }
  .generate-columns(@n, (@i + 1));
}
```

**CSS**
```CSS
.column-1 {
  width: 25%;
}
.column-2 {
  width: 50%;
}
.column-3 {
  width: 75%;
}
.column-4 {
  width: 100%;
}
```

## Using Mixins as Functions 当作函数来用

```less
.average(@x, @y) {
  @result: ((@x + @y) / 2);
}

div {
  // call a mixin and look up its "@return" value
  padding: .average(16px, 50px)[@result];
}
```
